version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: cinebook-db-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_prod_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - cinebook-network-prod

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cinebook-api-prod
    restart: always
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
    expose:
      - "5000"
    networks:
      - cinebook-network-prod

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cinebook-frontend-prod
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: /api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/ssl:/etc/nginx/ssl:ro
    networks:
      - cinebook-network-prod

volumes:
  mongodb_prod_data:
    driver: local

networks:
  cinebook-network-prod:
    driver: bridge
