apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cinebook
data:
  NODE_ENV: production
  PORT: "5000"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cinebook
type: Opaque
stringData:
  JWT_SECRET: your-secret-key-change-this
  STRIPE_SECRET_KEY: sk_test_your_key
  STRIPE_PUBLIC_KEY: pk_test_your_key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cinebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cinebook-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: STRIPE_PUBLIC_KEY
            - name: MONGO_URI
              value: "mongodb://cinebook:changeme@mongodb:27017/cinebook_db?authSource=admin"
            - name: CORS_ORIGIN
              value: "http://localhost"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cinebook
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
